variables:
  VSCODE_BUILD_VERBOSE: true

steps:

- task: NodeTool@0
  inputs:
    versionSpec: "8.9.1"

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    versionSpec: "1.3.2"

- script: |
    echo "machine monacotools.visualstudio.com password $(VSO_PAT)" > ~/.netrc
    yarn
    npm run gulp -- hygiene
    ./node_modules/.bin/tsc -p ./src/tsconfig.monaco.json --noEmit
    VSCODE_MIXIN_PASSWORD="$(VSCODE_MIXIN_PASSWORD)" npm run gulp -- mixin
    node build/tfs/common/installDistro.js

- script: |
    VSCODE_MIXIN_PASSWORD="$(VSCODE_MIXIN_PASSWORD)" npm run gulp -- vscode-darwin-min
  name: build

- script: |
    ./scripts/test.sh --build --reporter dot
    ./scripts/test-integration.sh
  name: test

- script: |
    ./build/tfs/darwin/release.sh
    npm run gulp -- upload-vscode-configuration