variables:
  VSCODE_BUILD_VERBOSE: true

steps:

- script: |
    apt-get update
    apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 libgconf-2-4 dbus xvfb
    cp build/tfs/linux/$(VSCODE_ARCH)/xvfb.init /etc/init.d/xvfb
    chmod +x /etc/init.d/xvfb
    update-rc.d xvfb defaults
    ln -sf /bin/dbus-daemon /usr/bin/dbus-daemon
    service xvfb start
    service dbus start

- task: NodeTool@0
  inputs:
    versionSpec: "8.9.1"

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    versionSpec: "1.3.2"

- script: |
    echo "machine monacotools.visualstudio.com password $(VSO_PAT)" > ~/.netrc
    yarn
    npm run gulp -- hygiene
    npm run monaco-compile-check
    VSCODE_MIXIN_PASSWORD="$(VSCODE_MIXIN_PASSWORD)" npm run gulp -- mixin
    node build/tfs/common/installDistro.js

- script: |
    VSCODE_MIXIN_PASSWORD="$(VSCODE_MIXIN_PASSWORD)" npm run gulp -- vscode-linux-$(VSCODE_ARCH)-min
  name: build

- script: |
    DISPLAY=:10 ./scripts/test.sh --build --tfs
  name: test