variables:
  VSCODE_BUILD_VERBOSE: true
  APPVEYOR: true

steps:

- task: NodeTool@0
  inputs:
    versionSpec: "8.9.1"

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    versionSpec: "1.3.2"

- task: PowerShell@1
  inputs:
    scriptType: inlineScript
    arguments: '-arch x64 -mixinPassword "$(VSCODE_MIXIN_PASSWORD)" -vsoPAT "$(VSO_PAT)"'
    inlineScript: |
      Param(
        [string]$arch,
        [string]$mixinPassword,
        [string]$vsoPAT
      )

      "machine monacotools.visualstudio.com password ${vsoPAT}" | Out-File "$env:HOME\_netrc" -Encoding ASCII
      $env:npm_config_arch="$arch"
      $env:CHILD_CONCURRENCY="1"
      yarn
      npm run gulp -- hygiene
      npm run monaco-compile-check
      $env:VSCODE_MIXIN_PASSWORD = $mixinPassword
      npm run gulp -- mixin
      node build/tfs/common/installDistro.js

- powershell: |
    $env:VSCODE_MIXIN_PASSWORD="$(VSCODE_MIXIN_PASSWORD)"
    npm run gulp -- "vscode-win32-$global:arch-min"
    npm run gulp -- "vscode-win32-$global:arch-copy-inno-updater"
  name: build

- powershell: |
    .\scripts\test.bat --build --tfs
  name: test