# Publish @types/vscode for each release

trigger:
  branches:
    include: ['octref/devops-publish-types', 'refs/tags/*']

steps:
- task: NodeTool@0
  inputs:
    versionSpec: "10.15.1"

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    versionSpec: "1.10.1"

- bash: |
    # Install build dependencies
    (cd build && yarn)
    node build/azure-pipelines/publish-types/check-version.js
  displayName: Check version

- bash: |
    git config user.email "vscode@microsoft.com"
    git config user.name "VSCode"

    git clone https://github.com/octref/vscode-DefinitelyTyped.git --depth=1

    cd vscode-DefinitelyTyped

    git remote add dt https://github.com/DefinitelyTyped/DefinitelyTyped.git
    git fetch dt
    git rebase dt/master

    cd ..

    node build/azure-pipelines/publish-types/update-types.js

    TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
    git commit -am 'VS Code $TAG_VERSION Extension API'
    git push origin master

  displayName: Update vscode-DefinitelyTyped
