parameters:
  - name: VSCODE_QUALITY
    type: string
  - name: VSCODE_BUILD_MACOS
    type: boolean
  - name: VSCODE_BUILD_MACOS_ARM64
    type: boolean
  - name: channel
    type: string
    default: stable

variables:
  - name: VSCODE_CLI_TARGETS
    value:
      - ${{ if eq(parameters.VSCODE_BUILD_MACOS, true) }}:
        - { target: x86_64-apple-darwin, artifact: unsigned_vscode_cli_darwin_x64_cli }
      - ${{ if eq(parameters.VSCODE_BUILD_MACOS_ARM64, true) }}:
        - { target: aarch64-apple-darwin, artifact: unsigned_vscode_cli_darwin_arm64_cli }

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"

  - template: ../mixin-distro-posix.yml
    parameters:
      VSCODE_QUALITY: ${{ variables.VSCODE_QUALITY }}

  - script: |
      set -e
      node build/azure-pipelines/cli/prepare.js
    displayName: Prepare CLI build
    env:
      GITHUB_TOKEN: "$(github-distro-mixin-password)"

  - template: ../cli/install-rust-posix.yml
    parameters:
      targets: ${{ variables.VSCODE_CLI_TARGETS }}

  - ${{ each target in variables.VSCODE_CLI_TARGETS }}:
    - script: cargo build --release --target ${{ target.target }} --bin=code-tunnel
      displayName: Compile ${{ target.artifact }}
      workingDirectory: $(Build.SourcesDirectory)/cli
      env:
        VSCODE_CLI_VERSION: $(VSCODE_CLI_VERSION)
        VSCODE_CLI_REMOTE_LICENSE_TEXT: $(VSCODE_CLI_REMOTE_LICENSE_TEXT)
        VSCODE_CLI_REMOTE_LICENSE_PROMPT: $(VSCODE_CLI_REMOTE_LICENSE_PROMPT)
        VSCODE_CLI_ASSET_NAME: ${{ target.artifact }}
        VSCODE_CLI_AI_KEY: $(VSCODE_CLI_AI_KEY)
        VSCODE_CLI_AI_ENDPOINT: $(VSCODE_CLI_AI_ENDPOINT)

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Build.SourcesDirectory)/cli/target/${{ target.target }}/release/code-tunnel
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/${{ target.artifact }}.zip

    - publish: $(Build.ArtifactStagingDirectory)/${{ target.artifact }}.zip
      artifact: ${{ target.artifact }}
      displayName: Publish ${{ target.artifact }} artifact
