name: @@NAME@@
version: @@VERSION@@
epoch: @@EPOCH@@
summary: Code editing. Redefined.
description: |
  Visual Studio Code is a new choice of tool that combines the
  simplicity of a code editor with what developers need for the core
  edit-build-debug cycle.

grade: stable
confinement: classic

parts:
  code:
    plugin: dump
    source: .
    # source: https://az764295.vo.msecnd.net/stable/27492b6bf3acb0775d82d2f87b25a93490673c6d/code_1.16.1-1505406497_amd64.deb
    # source-type: deb
    # Correct path to icon.
    # Remove translated Name[xx]=
    #  - Due to http://pad.lv/1662456
    # prepare: |
    #   sed -i 's|Icon=.code|Icon=/usr/share/pixmaps/code\.png|g' usr/share/applications/code.desktop
    #   sed -i '/^Name\[/d' usr/share/applications/code.desktop
    after:
      - desktop-gtk2
    stage-packages:
      - gconf2
      - libasound2
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6
    prime:
      - -usr/share/dh-python
  electron-launch:
    plugin: dump
    source: .
    organize:
      electron-launch: bin/electron-launch
    prime:
      - -monitor.sh
      - -OLD_VERSION
      - -*.bz2

apps:
  @@NAME@@:
    command: bin/electron-launch classic ${SNAP}/usr/share/@@NAME@@/bin/@@NAME@@
    desktop: usr/share/applications/@@NAME@@.desktop